import type { NextPage } from "next";
import Head from "next/head";
import { useRecoilValue } from "recoil";
import { ProductCard, NavBar } from "../components";
import { useInfinitePhotos } from "../hooks";
import likedListState from "../recoil/liked-list";

const Home: NextPage = () => {
  const { data, isError, isLoading, refCallback } = useInfinitePhotos();
  const likedList = useRecoilValue(likedListState);

  if (isError) return <div>Error</div>;
  if (isLoading) return <div>Loading</div>;

  return (
    <div className="mx-auto max-w-5xl">
      <Head>
        <title>Next Cart App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar></NavBar>
      <section className="grid grid-cols-4 gap-4">
        {data?.pages.map((page) =>
          page.photos.map(({ id, urls: { small: imgSrc }, likes }) => (
            <ProductCard
              key={id}
              id={id}
              imgSrc={imgSrc}
              price={likes * 1000}
              liked={likedList.map((x) => x.id).includes(id)}
            />
          ))
        )}
      </section>
      <div ref={refCallback}></div>
    </div>
  );
};

export default Home;
