import type { NextPage } from "next";
import Head from "next/head";
import { ProductCard } from "../components";
import { useInfinitePhotos } from "../hooks";

const Home: NextPage = () => {
  const { data, isError, isLoading, refCallback } = useInfinitePhotos();

  if (isError) return <div>Error</div>;
  if (isLoading) return <div>Loading</div>;

  return (
    <div className="mx-auto max-w-5xl">
      <Head>
        <title>Next Cart App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex p-2">
        <h1 className="mr-auto text-2xl font-bold">Soma Next Cart</h1>
        <nav>
          <ul className="flex justify-end gap-2">
            <li>제품 목록</li>
            <li>장바구니</li>
          </ul>
        </nav>
      </header>
      <section className="grid grid-cols-4 gap-4 p-4">
        {data?.pages.map((page) =>
          page.photos.map(({ id, urls: { small: imgSrc }, likes }) => (
            <ProductCard
              key={id}
              imgSrc={imgSrc}
              price={likes * 1000}
              liked={likes % 2 == 0}
            />
          ))
        )}
      </section>
      <div ref={refCallback}></div>
    </div>
  );
};

export default Home;
