import type { NextPage } from "next";
import Head from "next/head";
import { useRecoilValue } from "recoil";
import { NavBar, ProductCard } from "../components";
import likedListState from "../recoil/liked-list";

const Liked: NextPage = () => {
  const likedList = useRecoilValue(likedListState);

  return (
    <div className="mx-auto max-w-5xl">
      <Head>
        <title>Next Cart App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar></NavBar>
      <section className="grid grid-cols-4 gap-4">
        {likedList.map((product) => (
          <ProductCard
            key={product.id}
            id={product.id}
            imgSrc={product.imgSrc}
            price={product.price}
            liked={true}
          />
        ))}
      </section>
    </div>
  );
};

export default Liked;
